
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - contextmapper.context-mapper-vscode-extension