name: Java CI

on:
  push:
    branches:
      - develop
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency: staging_environment

jobs:
 GradleJob:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu, macos, windows]
        java_version: [16]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt'
      - name: Gradle check
        working-directory: ./Trasporti116-117
        run: |
          chmod +x ./gradlew
          ./gradlew check

